---
- name: Check Operating System
  fail:
    msg="You're not running a supported operating system (CentOS, RHEL 7+, Fedora or FreeBSD)"
  when: ((ansible_os_family != "RedHat" or ansible_os_family != "FreeBSD")
          and (ansible_distribution_major_version|int < 7))

- name: Import EPEL GPG Key
  rpm_key: key=https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
    state=present
  become: true
  when: ansible_distribution_major_version|int <= 7 and ansible_os_family == "RedHat"

- name: Check for EPEL repo
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state=present
  become: true
  when: ansible_distribution_major_version|int <= 7 and ansible_os_family == "RedHat"

- name: Install NRPE and Common Plugins
  yum:
    name: ['nrpe', 'nagios-plugins-load', 'nagios-plugins-uptime', 'nagios-plugins-swap', 'nagios-plugins-procs',
    'nagios-plugins-users', 'nagios-plugins-disk', 'nagios-plugins-tcp']
    state: present
  become: true
  when: ansible_distribution_major_version|int <= 7 and ansible_os_family == "RedHat"

- name: Install libsemanage-python
  yum:
    name: ['libsemanage-python']
    state: present
  become: true
  when: ansible_distribution_major_version|int <= 7 and ansible_os_family == "RedHat"
  ignore_errors: true

- name: Setup NRPE client configuration
  template:
    src=nrpe.cfg.j2
    dest=/etc/nagios/nrpe.cfg
    force=yes
  become: true
  when: ansible_system == "Linux"

- name: Start NRPE service
  command: systemctl restart nrpe.service
  ignore_errors: true
  when: ansible_distribution_major_version|int >= 7 and ansible_system == "Linux"
  become: true

- name: Set NRPE to start on boot
  command: systemctl enable nrpe.service
  ignore_errors: true
  when: ansible_distribution_major_version|int >= 7 and ansible_os_family == "RedHat"
  become: true

